debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{PROXY_DOMAIN}"
watch = true
exposedByDefault = false
